# Generated by Django 4.1.7 on 2023-05-15 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(max_length=20)),
                ('Lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='firstaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to='static/')),
                ('steps', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('Lat', models.CharField(blank=True, max_length=20, null=True)),
                ('Lng', models.CharField(blank=True, max_length=20, null=True)),
                ('is_doctor', models.BooleanField()),
                ('doctorId', models.ImageField(blank=True, null=True, upload_to='img')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('online', models.BooleanField(null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.ambulance')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CheckupForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('msg_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to='API.profile')),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='API.profile')),
            ],
        ),
    ]
