# Generated by Django 4.1.7 on 2023-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_requesthospital_usercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='password', max_length=16),
            preserve_default=False,
        ),
    ]
