# Generated by Django 4.1.7 on 2023-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_profile_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
