# Generated by Django 4.1.7 on 2023-06-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_profile_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
