# Generated by Django 4.1.7 on 2023-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_chatmessage_pic_alter_chatmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
