# Generated by Django 4.1.7 on 2023-06-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_profile_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
